import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./Components/provider/AuthProvider";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer, toast } from "react-toastify";
import Head from "next/head";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: 'Expense Tracker',
  description: 'Generated by create next app',
}

export default function RootLayout({children}) {
  

  return (
    <html lang="en">
      <body >
       <AuthProvider>{children}</AuthProvider>
     <ToastContainer/>
      </body>
    </html>
  );
}

